### ISSUE TITLE
There are no methods available

### ISSUE THREAD

**Issue by vasco3** [Colingo/mixpanel-browserify#1]
The only method that seems to work is init()

**Comment by milosh012** [comment]
Hi @vasco3 how you resolved this issue? I also can not run standard mixpanel methods...

**Comment by nuthinking** [comment]
Does this library work?

**Comment by vasco3** [comment]
hey @milosh012  I don't have access anymore to the code base where I used this library. I had to use dev tools to see how the objects created by the library behaved until I found the way to get access to the methods. I'm almost sure I had to assign that module to a method on _window_ (browser local variable).
