### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by yocontra** [Colingo/mixpanel-browserify#3]
this is 2yrs old

**Comment by Raynos** [comment]
yeah lol.

**Comment by Raynos** [comment]
Hopefully mixpanel fixed their client by now to be a nice thing.

I havnt used mixpanel in two years so this code is pretty much useless

**Comment by yocontra** [comment]
@Raynos no :( lol

Where did you get the unminified version of the code from? I think they only serve a minified one now

**Comment by Raynos** [comment]
@contra your drunk bro.

I downloaded it from github https://github.com/mixpanel/mixpanel-js/blob/master/mixpanel.js

**Comment by Raynos** [comment]
@contra just clone ( https://github.com/mixpanel/mixpanel-js/blob/master/package.json ); add a browser field and npm publish XD

**Comment by Raynos** [comment]
@contra just clone ( https://github.com/mixpanel/mixpanel-js/blob/master/package.json ); add a browser field and npm publish XD

**Comment by yocontra** [comment]
@Raynos shit didn't realize they had a github for it...
